name: JD_Sign_Action

on:
  repository_dispatch:
  release:
    types: published
  # push:
  #   branches:
  #     - master
#   schedule:
#     - cron: 30 20 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: ${{ secrets.JD_COOKIE }}
  JD_DUAL_COOKIE: ${{ secrets.JD_DUAL_COOKIE }}
  PUSH_KEY: ${{ secrets.PUSH_KEY }}
  APPID: ${{ secrets.APPID }}
  SECRET: ${{ secrets.SECRET }}
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node jd_sign.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt
            - name: Commit files
              run: |
                git config --local user.email "19820637553@163.com"
                git config --local user.name "XXXShaunPan"
                git add .
                git commit -m "`date '+%Y-%m-%d %H:%M:%S'`"
                git push -u origin master && echo "push ok"
